databases:
  - name: nogadb
    plan: free
    databaseName: nogadb_q4lv
    user: nogadb_q4lv_user

services:
  - type: web
    plan: free
    name: NOGA
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "daphne -p 8000 -b 0.0.0.0 NOGA.asgi:application"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: NOGAdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4