# Generated by Django 5.0.6 on 2025-05-31 15:23

import NOGA.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_number', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='test@gmail.com', max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.BooleanField()),
                ('salary', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=100)),
                ('date_of_employment', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=NOGA.utils.upload_to, validators=[NOGA.utils.validate_image_size])),
                ('job_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='employees.job_type')),
            ],
        ),
    ]
