# Generated by Django 5.0.6 on 2025-07-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
