# Generated by Django 5.0.6 on 2025-07-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
