# Generated by Django 5.0.6 on 2025-07-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='base_salary',
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
