# Generated by Django 5.0.6 on 2025-07-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_base_salary_alter_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_vecation', 'On Vecation')], default='on_time', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_vecation', 'On Vecation')], default='on_time', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_vecation', 'On Vecation')], max_length=20),
        ),
    ]
