# Generated by Django 5.0.6 on 2025-07-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_attendance_check_in_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='late_count',
            new_name='late_or_left_early_count',
        ),
    ]
