# Generated by Django 5.0.6 on 2025-07-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='employee',
        ),
    ]
