# Generated by Django 5.0.6 on 2025-07-15 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_workschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='start_time',
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_working_day', models.BooleanField(default=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='employees.workschedule')),
            ],
            options={
                'unique_together': {('schedule', 'day')},
            },
        ),
    ]
