# Generated by Django 5.0.6 on 2025-07-17 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_workschedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vecation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vecation_type', models.CharField(choices=[('paid', 'مدفوعة'), ('unpaid', ' غير مدفوعة')], max_length=10)),
                ('duration_type', models.CharField(choices=[('daily', 'يومية'), ('monthly', 'شهرية')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employees.employee')),
            ],
        ),
    ]
