# Generated by Django 5.0.6 on 2025-06-08 17:36

import NOGA.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_number', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='test@gmail.com', max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.BooleanField()),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=NOGA.utils.upload_to, validators=[NOGA.utils.validate_image_size])),
            ],
        ),
    ]
