# Generated by Django 5.0.6 on 2025-05-31 15:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='app_user_information',
            new_name='Client_Profile',
        ),
    ]
