# Generated by Django 5.0.6 on 2025-09-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedents', models.JSONField(default=list, help_text='المنتجات التي تم شرائها معاً')),
                ('consequents', models.JSONField(default=list, help_text='قائمة بالمنتجات المقترحة')),
                ('support', models.FloatField(help_text='معدل تكرار هذه المجموعة في البيانات ')),
                ('confidence', models.FloatField(help_text='قوة العلاقة بين المنتجات')),
                ('lift', models.FloatField(help_text='مقياس قوة الارتباط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-lift', '-confidence'],
                'indexes': [models.Index(fields=['lift'], name='mobile_asso_lift_aee93a_idx'), models.Index(fields=['confidence'], name='mobile_asso_confide_9ebec0_idx')],
            },
        ),
    ]
