# Generated by Django 5.0.6 on 2025-06-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('products', '0003_rename_attribute_attribute_unit_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.variant')),
            ],
        ),
    ]
