# Generated by Django 5.0.6 on 2025-08-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_camera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='url',
            new_name='source_url',
        ),
        migrations.AddField(
            model_name='camera',
            name='view_url',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
