# Generated by Django 5.0.6 on 2025-09-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_rename_url_camera_source_url_camera_view_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='area_points',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
