# Generated by Django 5.0.6 on 2025-06-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_variant_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('discount_type', models.CharField(choices=[('fixed', 'fixed'), ('percentage', 'percentage')], max_length=30)),
                ('has_products', models.BooleanField()),
                ('has_categories', models.BooleanField()),
                ('for_every_product', models.BooleanField(default=False)),
                ('for_every_product_exept', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Discount_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_options', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Discount_Category_Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.discount_category')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.option')),
            ],
        ),
        migrations.AddField(
            model_name='discount_category',
            name='options',
            field=models.ManyToManyField(through='sales.Discount_Category_Option', to='products.option'),
        ),
        migrations.CreateModel(
            name='Discount_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_options', models.BooleanField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.discount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Discount_Product_Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.discount_product')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.option')),
            ],
        ),
        migrations.AddField(
            model_name='discount_product',
            name='options',
            field=models.ManyToManyField(through='sales.Discount_Product_Option', to='products.option'),
        ),
    ]
