# Generated by Django 5.0.6 on 2025-08-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchased_offers',
        ),
        migrations.RemoveField(
            model_name='purchased_products',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offer_product',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offer_product',
            name='options',
        ),
        migrations.RemoveField(
            model_name='offer_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='offer_product_option',
            name='offer_product',
        ),
        migrations.RemoveField(
            model_name='offer_product_option',
            name='option',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='has_offers',
        ),
        migrations.RemoveField(
            model_name='purchased_products',
            name='in_pack',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Offer_Product',
        ),
        migrations.DeleteModel(
            name='Offer_Product_Option',
        ),
    ]
