# Generated by Django 5.0.6 on 2025-07-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variant_sku'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_options', models.BooleanField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Offer_Product_Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.offer_product')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.option')),
            ],
        ),
        migrations.AddField(
            model_name='offer_product',
            name='options',
            field=models.ManyToManyField(through='sales.Offer_Product_Option', to='products.option'),
        ),
    ]
