# Generated by Django 5.0.6 on 2025-08-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_purchase_purchased_offers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='has_coupons',
            new_name='has_coupon',
        ),
    ]
