# Generated by Django 5.0.6 on 2025-07-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_offer_offer_product_offer_product_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('discount_type', models.CharField(choices=[('fixed', 'fixed'), ('percentage', 'percentage')], max_length=30)),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
