# Generated by Django 5.0.6 on 2025-08-29 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_varaint_variant_image_variant'),
        ('sales', '0003_rename_has_coupons_purchase_has_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_products',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.discount'),
        ),
        migrations.AlterField(
            model_name='purchased_products',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variant'),
        ),
        migrations.AlterField(
            model_name='purchased_products',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.purchase'),
        ),
        migrations.AlterField(
            model_name='purchased_products',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='purchased_products',
            unique_together={('purchase', 'product')},
        ),
        migrations.CreateModel(
            name='AssociationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedents', models.JSONField(help_text='المنتجات التي تم شرائها معاً')),
                ('consequents', models.JSONField(help_text='قائمة بالمنتجات المقترحة')),
                ('support', models.FloatField(help_text='معدل تكرار هذه المجموعة في البيانات ')),
                ('confidence', models.FloatField(help_text='قوة العلاقة بين المنتجات')),
                ('lift', models.FloatField(help_text='مقياس قوة الارتباط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lift'], name='sales_assoc_lift_b8a36f_idx'), models.Index(fields=['confidence'], name='sales_assoc_confide_a182b5_idx')],
            },
        ),
    ]
