# Generated by Django 5.0.6 on 2025-07-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='jk123m3', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
