# Generated by Django 5.0.6 on 2025-08-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_purchased_products_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associationrule',
            options={'ordering': ['-lift', '-confidence']},
        ),
    ]
