# Generated by Django 5.0.6 on 2025-07-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='max_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_price',
            field=models.FloatField(null=True),
        ),
    ]
