# Generated by Django 5.0.6 on 2025-07-12 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('products', '0003_variant_sku'),
        ('sales', '0005_alter_coupon_max_price_alter_coupon_min_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_number', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('gender', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=100)),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtotal_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('has_coupon', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Purchased_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wholesale_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('has_discount', models.BooleanField(default=False)),
                ('in_pack', models.BooleanField(default=False)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.discount')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.variant')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.purchase')),
            ],
        ),
    ]
