# Generated by Django 5.0.6 on 2025-09-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_associationrule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationrule',
            name='antecedents',
            field=models.JSONField(default=list, help_text='المنتجات التي تم شرائها معاً'),
        ),
        migrations.AlterField(
            model_name='associationrule',
            name='consequents',
            field=models.JSONField(default=list, help_text='قائمة بالمنتجات المقترحة'),
        ),
    ]
