# Generated by Django 5.0.6 on 2025-07-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_customer_purchase_purchased_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_products',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
