# Generated by Django 5.0.6 on 2025-09-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_associationrule_antecedents_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssociationRule',
        ),
    ]
