# Generated by Django 5.0.6 on 2025-09-07 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_varaint_variant_image_variant'),
        ('sales', '0007_delete_associationrule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchased_products',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='discount_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='discount_category',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.discount'),
        ),
        migrations.AlterField(
            model_name='discount_category_option',
            name='discount_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.discount_category'),
        ),
        migrations.AlterField(
            model_name='discount_category_option',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.option'),
        ),
        migrations.AlterField(
            model_name='discount_product',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.discount'),
        ),
        migrations.AlterField(
            model_name='discount_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='discount_product_option',
            name='discount_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.discount_product'),
        ),
        migrations.AlterField(
            model_name='discount_product_option',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.option'),
        ),
    ]
