# Generated by Django 5.0.6 on 2025-07-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_purchased_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='national_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
