# Generated by Django 5.0.6 on 2025-07-14 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_customer_national_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.coupon'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='subtotal_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
