# Generated by Django 5.0.6 on 2025-07-14 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_purchase_coupon_alter_purchase_subtotal_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_products',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.discount'),
        ),
        migrations.AlterField(
            model_name='purchased_products',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.offer'),
        ),
    ]
