# Generated by Django 5.0.6 on 2025-07-16 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variant_sku'),
        ('sales', '0010_alter_purchased_products_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='has_coupon',
            new_name='has_coupons',
        ),
        migrations.AlterUniqueTogether(
            name='purchased_products',
            unique_together={('purchase', 'product')},
        ),
        migrations.AddField(
            model_name='purchase',
            name='has_offers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.offer'),
        ),
        migrations.RemoveField(
            model_name='purchased_products',
            name='in_pack',
        ),
        migrations.RemoveField(
            model_name='purchased_products',
            name='offer',
        ),
    ]
