# Generated by Django 5.0.6 on 2025-07-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_rename_has_coupon_purchase_has_coupons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='offer',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchased_offers',
            field=models.ManyToManyField(null=True, to='sales.offer'),
        ),
    ]
