# Generated by Django 5.0.6 on 2025-07-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_remove_purchase_offer_purchase_purchased_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchased_offers',
            field=models.ManyToManyField(to='sales.offer'),
        ),
    ]
