# Generated by Django 5.0.6 on 2025-07-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_purchase_purchased_offers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchased_products',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='offer_product',
            name='qunatity',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
