# Generated by Django 5.0.6 on 2025-07-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_purchased_products_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer_product',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
