# Generated by Django 5.0.6 on 2025-07-17 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_rename_qunatity_offer_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_products',
            name='in_pack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchased_products',
            name='offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sales.offer'),
            preserve_default=False,
        ),
    ]
