# Generated by Django 5.0.6 on 2025-07-17 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_purchased_products_in_pack_purchased_products_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_products',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.offer'),
        ),
    ]
