# Generated by Django 5.0.6 on 2025-07-21 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=50)),
                ('attribute_type', models.CharField(choices=[('number', 'number'), ('string', 'string')], max_length=30)),
                ('is_multivalue', models.BooleanField(default=False)),
                ('is_categorical', models.BooleanField(default=False)),
                ('has_unit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Category_Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.attribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(through='products.Category_Attribute', to='products.attribute'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.CharField(blank=True, max_length=300, null=True)),
                ('qr_codes_download', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
                ('linked_products', models.ManyToManyField(to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Linked_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_to_products', to='products.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product1', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_status', models.CharField(choices=[('packaging:', 'packaging:'), ('transporting', 'transporting'), ('delivered', 'delivered'), ('confirmed', 'confirmed')], default='packaging', max_length=30)),
                ('code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transported_at', models.DateTimeField(null=True)),
                ('received_at', models.DateTimeField(null=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_branch', to='branches.branch')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_branch', to='branches.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Transport_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('fully-approved', 'fully-approved'), ('partially-approved', 'partially-approved'), ('waiting', 'waiting'), ('rejected', 'rejected')], default='waiting', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('transportation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='Option_Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.option')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute_Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.attribute')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.unit')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='units',
            field=models.ManyToManyField(through='products.Attribute_Unit', to='products.unit'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('wholesale_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('sku', models.CharField(max_length=300)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transported_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.transportation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Requested_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_request_status', models.CharField(choices=[('fully-approved', 'fully-approved'), ('partially-approved', 'partially-approved'), ('waiting', 'waiting'), ('rejected', 'rejected')], default='waiting', max_length=30)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.transport_request')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Received_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.transportation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Variant_Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.option')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.variant')),
            ],
        ),
        migrations.AddField(
            model_name='variant',
            name='options',
            field=models.ManyToManyField(through='products.Variant_Option', to='products.option'),
        ),
    ]
