# Generated by Django 5.0.6 on 2025-07-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='qr_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='qr_codes_download',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
