# Generated by Django 5.0.6 on 2025-06-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
