# Generated by Django 5.0.6 on 2025-06-10 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='linked_products',
            field=models.ManyToManyField(to='products.product'),
        ),
        migrations.CreateModel(
            name='Linked_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_to_products', to='products.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product1', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation_status', models.CharField(choices=[('packaging:', 'packaging:'), ('transporting', 'transporting'), ('delivered', 'delivered'), ('confirmed', 'confirmed')], default='packaging', max_length=30)),
                ('code', models.CharField(max_length=100)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_branch', to='branches.branch')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_branch', to='branches.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Transported_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.variant')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.transportation')),
            ],
        ),
    ]
