# Generated by Django 5.0.6 on 2025-06-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='received_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='transported_at',
            field=models.DateTimeField(null=True),
        ),
    ]
