# Generated by Django 5.0.6 on 2025-06-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_unit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='units',
            field=models.ManyToManyField(blank=True, to='products.unit'),
        ),
    ]
