# Generated by Django 5.0.6 on 2025-06-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_linked_products_linked_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute_unit',
            old_name='Attribute',
            new_name='attribute',
        ),
    ]
