# Generated by Django 5.0.6 on 2025-06-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_transportation_received_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='sku',
            field=models.CharField(default='sku', max_length=300),
            preserve_default=False,
        ),
    ]
