# Generated by Django 5.0.6 on 2025-06-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_attribute_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='units',
            field=models.ManyToManyField(to='products.unit'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category'),
        ),
        migrations.AlterField(
            model_name='option',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.attribute'),
        ),
        migrations.AlterField(
            model_name='option_unit',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category'),
        ),
        migrations.AlterField(
            model_name='varient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
