# Generated by Django 5.0.6 on 2025-06-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_attribute_attribute_unit_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_attribute',
            old_name='Attribute',
            new_name='attribute',
        ),
    ]
