# Generated by Django 5.0.6 on 2025-06-10 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_attribute_category_attribute_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Received_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.variant')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.transportation')),
            ],
        ),
    ]
