# Generated by Django 5.0.6 on 2025-06-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_attribute_units_alter_category_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
