# Generated by Django 5.0.6 on 2025-07-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image_image_variant_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant_image',
            old_name='varaint',
            new_name='variant',
        ),
    ]
