# Generated by Django 5.0.6 on 2025-06-11 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_products'),
        ('products', '0005_received_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_branch', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='variant_option',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.option'),
        ),
    ]
