# Generated by Django 5.0.6 on 2025-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_varaint_variant_image_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='transportation_status',
            field=models.CharField(choices=[('packaging:', 'packaging'), ('transporting', 'transporting'), ('delivered', 'delivered'), ('confirmed', 'confirmed')], default='packaging', max_length=30),
        ),
    ]
