# Generated by Django 5.0.6 on 2025-09-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_transportation_transportation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='transportation_status',
            field=models.CharField(choices=[('packaging', 'packaging'), ('transporting', 'transporting'), ('delivered', 'delivered'), ('confirmed', 'confirmed')], default='packaging', max_length=30),
        ),
    ]
